# Generated by Django 2.0 on 2018-03-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(default=1)),
                ('layerType', models.CharField(max_length=20)),
                ('kernelAmount', models.IntegerField(default=0)),
                ('kernelSize', models.IntegerField(default=0)),
                ('neuronAmount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Информация о слое',
                'verbose_name_plural': 'Информация о слоях',
            },
        ),
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('isCreated', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Модель НН',
                'verbose_name_plural': 'Модели НН',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.NetworkModel')),
            ],
            options={
                'verbose_name': 'Весовые коэффициенты',
                'verbose_name_plural': 'Весовые коэффициенты',
            },
        ),
        migrations.RemoveField(
            model_name='layerinfo',
            name='layerType',
        ),
        migrations.RemoveField(
            model_name='layerinfo',
            name='model',
        ),
        migrations.DeleteModel(
            name='LayerInfo',
        ),
        migrations.DeleteModel(
            name='LayerType',
        ),
        migrations.DeleteModel(
            name='NnModel',
        ),
        migrations.AddField(
            model_name='networklayers',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.NetworkModel'),
        ),
        migrations.AlterUniqueTogether(
            name='networklayers',
            unique_together={('orderNumber', 'model')},
        ),
    ]
