# Generated by Django 2.0 on 2018-03-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180324_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Тип слоя',
                'verbose_name_plural': 'Типы слоев',
            },
        ),
        migrations.AlterField(
            model_name='networklayers',
            name='layerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.LayerType'),
        ),
    ]
